"""

Revision ID: 6e8538aa23e5
Revises: dff50dbc1c07
Create Date: 2021-10-05 14:57:54.278698

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '6e8538aa23e5'
down_revision = 'dff50dbc1c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
