"""

Revision ID: 8899305f2af1
Revises: 6e8538aa23e5
Create Date: 2021-10-05 15:40:13.270344

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '8899305f2af1'
down_revision = '6e8538aa23e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_options', sa.Column('option', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision_options', 'option')
    # ### end Alembic commands ###
