"""

Revision ID: f2e8a31514f0
Revises: 021efe19ea05
Create Date: 2021-10-05 17:55:12.890084

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields

# revision identifiers, used by Alembic.
revision = 'f2e8a31514f0'
down_revision = '021efe19ea05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
