"""

Revision ID: 437b35cf808e
Revises: e3c50748b65f
Create Date: 2021-10-05 16:56:34.110916

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '437b35cf808e'
down_revision = 'e3c50748b65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decision_options', 'option',
               existing_type=mysql.ENUM('approved', 'denied'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decision_options', 'option',
               existing_type=mysql.ENUM('approved', 'denied'),
               nullable=True)
    # ### end Alembic commands ###
