"""

Revision ID: 4b2ea07259da
Revises: bb058c2861bd
Create Date: 2021-10-05 13:11:34.030500

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '4b2ea07259da'
down_revision = 'bb058c2861bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_line_items', sa.Column('decision', sa.Enum('approved', 'denied', name='claimlineitemtypedecisionenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_line_items', 'decision')
    # ### end Alembic commands ###
