"""

Revision ID: 0d3d2f153587
Revises: f2e8a31514f0
Create Date: 2021-10-06 13:59:55.839692

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '0d3d2f153587'
down_revision = 'f2e8a31514f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
