"""

Revision ID: e3c50748b65f
Revises: 00745cd8a7e3
Create Date: 2021-10-05 16:38:58.878467

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'e3c50748b65f'
down_revision = '00745cd8a7e3'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
