"""

Revision ID: 00745cd8a7e3
Revises: 8899305f2af1
Create Date: 2021-10-05 15:58:52.123147

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '00745cd8a7e3'
down_revision = '8899305f2af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_options')
    op.create_table('decision_options',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('deleted_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', src.models.fields.uuid.UUID(length=16), nullable=False),
    sa.Column('option', sa.Enum('approved', 'denied',
                                    name='decisionoptionenum')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
