"""

Revision ID: 5abe1893125e
Revises: 437b35cf808e
Create Date: 2021-10-05 16:57:45.492899

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from src.models.fields import uuid

from src.models.fields import UUID


# revision identifiers, used by Alembic.
revision = '5abe1893125e'
down_revision = '437b35cf808e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    id = UUID()
    op.execute("INSERT INTO decision_options (`id`, `option`) VALUES('" + str(id) + "', 'approved')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
