"""

Revision ID: 021efe19ea05
Revises: 5abe1893125e
Create Date: 2021-10-05 17:53:21.838206

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields

from src.models.fields import UUID

# revision identifiers, used by Alembic.
revision = '021efe19ea05'
down_revision = '5abe1893125e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
